spring:
  application:
    name: currency-calculation-service
    
server:
  port: 4444
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

currency-exchange-service:
  ribbon:
    listOfServers: http://localhost:2222, http://localhost:3333
    
