
spring:
  application:
    name: spring-cloud-config-server        
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vikashvs36/spring-cloud-config-store
          search-paths: "*service"
    
server:
  port: 8888
  