
spring:
  application:
    name: currency-exchange-service
    
#  datasource:
#    url: jdbc:mysql://localhost:3306/currency_exchange_db?createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true 
    
server:
  port: 2222
  
